package pl.kielce.tu.libraryApp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * @author ciepluchs
 */
@DynamoDBTable(tableName = "reservation")
public class Reservation implements Serializable {

    private static final long serialVersionUID = 1L;
    private static final int RESERVATION_PERIOD_IN_DAYS = 7;

    private String id;
    private User reservationOwner;
    private Book reservedBook;
    private ZonedDateTime creationDate;
    private ZonedDateTime reservationDue;

    public Reservation(User reservationOwner, Book reservedBook) {
        this.reservationOwner = reservationOwner;
        this.reservedBook = reservedBook;
        creationDate = ZonedDateTime.now();
        reservationDue = creationDate.plusDays(RESERVATION_PERIOD_IN_DAYS);
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "reservationOwner")
    public User getReservationOwner() {
        return reservationOwner;
    }

    public void setReservationOwner(User reservationOwner) {
        this.reservationOwner = reservationOwner;
    }

    @DynamoDBAttribute(attributeName = "reservedBook")
    public Book getReservedBook() {
        return reservedBook;
    }

    public void setReservedBook(Book reservedBook) {
        this.reservedBook = reservedBook;
    }

    @DynamoDBAttribute(attributeName = "creationDate")
    public ZonedDateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(ZonedDateTime creationDate) {
        this.creationDate = creationDate;
    }

    @DynamoDBAttribute(attributeName = "reservationDue")
    public ZonedDateTime getReservationDue() {
        return reservationDue;
    }

    public void setReservationDue(ZonedDateTime reservationDue) {
        this.reservationDue = reservationDue;
    }
}
